source 'https://rubygems.org'

gem 'rake'
gem 'activesupport'
gem 'httparty'

group :development, :test do
  gem 'pry'
  gem 'rspec'
  gem 'awesome_print'
  if ENV['X_PACT_DEVELOPMENT'] == 'true'
    gem 'pact', path: '../pact-ruby'
    gem 'pact-ffi', path: '../pact-ffi'
  else
    gem 'pact'
    gem 'pact-ffi'
  end
end
