source 'https://rubygems.org'

gem 'activesupport'
gem 'httparty'
gem 'rake'

group :development, :test do
  gem 'awesome_print'
  gem 'combustion'
  gem 'pry'
  gem 'rspec'
end

if ENV['X_PACT_DEVELOPMENT']
  gem 'pact', path: '../pact-ruby'
else
  gem 'pact', git: 'https://github.com/safdotdev/pact-ruby.git', branch: 'feat/pact-ruby-v2-conditional-install'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]

