source 'https://rubygems.org'

gem 'activesupport'
gem 'httparty'
gem 'rake'

group :development, :test do
  gem 'awesome_print'
  gem 'combustion'
  gem 'pry'
  gem 'rspec'
end

if ENV['X_PACT_DEVELOPMENT']
  gem 'sbmt-pact', path: '../../sbmt-pact'
else
  gem 'sbmt-pact', git: 'https://github.com/YOU54F/sbmt-pact.git', branch: 'feat/pact-ruby'
end
