require 'rubygems'
require 'bundler'

ENV['PACT_RUBY_V2_ENABLE'] = 'true'
ENV['PACT_RUBY_V1_ENABLE'] = 'false'

begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  warn e.message
  warn 'Run `bundle install` to install missing gems'
  exit e.status_code
end

require 'rake'
require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec)

task default: [:spec]

RSpec::Core::RakeTask.new('pact:spec') do |task|
  task.pattern = 'spec/pact/providers/**/*_spec.rb'
  task.rspec_opts = ['-t pact_v2']
end

$:.unshift 'lib'

desc 'Run the client'
task :run_client do
  require 'client'
  require 'ap'
  ap Client.new.process_data
end
