# encoding: utf-8

require 'rubygems'
require 'bundler'

ENV['PACT_RUBY_V2_ENABLE'] = 'true'
ENV['PACT_RUBY_V1_ENABLE'] = 'false'

begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end

require 'rake'
require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec)

RSpec::Core::RakeTask.new('pact:verify') do |task|
  task.pattern = 'spec/pact/consumers/**/*_spec.rb'
  task.rspec_opts = ['-t pact']
end


task :default => [:spec]

$:.unshift 'lib'
